package order;

import java.util.TreeSet;

import itemInterfaces.ItemInterface;

public interface OrderInterface {
  /**
   * Calculate the total price of the order.
   * 
   * @return
   */
  public double calculateTotal();

  /**
   * Calculate total frequent rental point generated by completing the order.
   * 
   * @return
   */
  public int calculateTotalPoint();

  /**
   * Return all rentals as an ordered set.
   * 
   * @return
   */
  public TreeSet<ItemInterface> getItems();

  /**
   * Return an XML formatted string. Intended for a decorator. For a composite
   * object, it will return multiple statements in XML.
   * 
   * @return
   */
  public String toXML();
}
